#include "config.hpp"
#include <borealis.hpp>
#include <fstream>
#include <filesystem>
#include <sstream>

namespace pkdex {

std::string Config::getConfigFilePath() {
    // Create the config directory if it doesn't exist
    std::filesystem::path configDir = "/config/pkDex";
    if (!std::filesystem::exists(configDir)) {
        try {
            std::filesystem::create_directories(configDir);
        } catch (const std::exception& e) {
            brls::Logger::error("Failed to create config directory: {}", e.what());
            return "";
        }
    }

    return configDir / "config.ini";
}

std::map<std::string, std::string> Config::readConfigFile() {
    std::map<std::string, std::string> config;
    std::string configPath = getConfigFilePath();
    
    if (configPath.empty()) {
        return config;
    }

    std::ifstream file(configPath);
    if (!file.is_open()) {
        // File doesn't exist yet, which is fine
        return config;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            continue;
        }

        // Parse key=value pairs
        size_t equalsPos = line.find('=');
        if (equalsPos != std::string::npos) {
            std::string key = line.substr(0, equalsPos);
            std::string value = line.substr(equalsPos + 1);
            config[key] = value;
        }
    }

    return config;
}

bool Config::writeConfigFile(const std::map<std::string, std::string>& config) {
    std::string configPath = getConfigFilePath();
    
    if (configPath.empty()) {
        return false;
    }

    std::ofstream file(configPath);
    if (!file.is_open()) {
        brls::Logger::error("Failed to open config file for writing: {}", configPath);
        return false;
    }

    // Write header
    file << "# pkDex configuration file\n";
    file << "# This file is automatically generated\n\n";

    // Write key-value pairs
    for (const auto& [key, value] : config) {
        file << key << "=" << value << "\n";
    }

    return true;
}

bool Config::getBool(const std::string& key, bool defaultValue) {
    auto config = readConfigFile();
    auto it = config.find(key);
    
    if (it == config.end()) {
        return defaultValue;
    }

    // Convert string to bool
    return it->second == "1" || it->second == "true" || it->second == "yes" || it->second == "on";
}

bool Config::setBool(const std::string& key, bool value) {
    auto config = readConfigFile();
    config[key] = value ? "1" : "0";
    return writeConfigFile(config);
}

} // namespace pkdex