#include "config.hpp"
#include <borealis.hpp>
#include <fstream>
#include <filesystem>
#include <sstream>

namespace pkdex {

std::string Config::getConfigFilePath() {
    // Create the config directory if it doesn't exist
    std::filesystem::path configDir = "/config/pkDex";
    if (!std::filesystem::exists(configDir)) {
        try {
            std::filesystem::create_directories(configDir);
        } catch (const std::exception& e) {
            brls::Logger::error("Failed to create config directory: {}", e.what());
            return "";
        }
    }

    return configDir / "config.ini";
}

std::map<std::string, std::string> Config::readConfigFile() {
    std::map<std::string, std::string> config;
    std::string configPath = getConfigFilePath();

    if (configPath.empty()) {
        return config;
    }

    std::ifstream file(configPath);
    if (!file.is_open()) {
        // File doesn't exist yet, which is fine
        return config;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            continue;
        }

        // Parse key=value pairs
        size_t equalsPos = line.find('=');
        if (equalsPos != std::string::npos) {
            std::string key = line.substr(0, equalsPos);
            std::string value = line.substr(equalsPos + 1);
            config[key] = value;
        }
    }

    return config;
}

bool Config::writeConfigFile(const std::map<std::string, std::string>& config) {
    std::string configPath = getConfigFilePath();

    if (configPath.empty()) {
        return false;
    }

    std::ofstream file(configPath);
    if (!file.is_open()) {
        brls::Logger::error("Failed to open config file for writing: {}", configPath);
        return false;
    }

    // Write header
    file << "# pkDex configuration file\n";
    file << "# This file is automatically generated\n\n";

    // Write key-value pairs
    for (const auto& [key, value] : config) {
        file << key << "=" << value << "\n";
    }

    return true;
}

bool Config::getBool(const std::string& key, bool defaultValue) {
    auto config = readConfigFile();
    auto it = config.find(key);

    if (it == config.end()) {
        return defaultValue;
    }

    // Convert string to bool
    return it->second == "1" || it->second == "true" || it->second == "yes" || it->second == "on";
}

bool Config::updateConfigKey(const std::string& key, const std::string& value) {
    std::string configPath = getConfigFilePath();

    if (configPath.empty()) {
        return false;
    }

    // Read the existing file
    std::ifstream inFile(configPath);
    if (!inFile.is_open()) {
        // File doesn't exist yet, create it with just this key-value pair
        std::ofstream outFile(configPath);
        if (!outFile.is_open()) {
            brls::Logger::error("Failed to create config file: {}", configPath);
            return false;
        }

        outFile << "# pkDex configuration file\n";
        outFile << "# This file is automatically generated\n\n";
        outFile << key << "=" << value << "\n";
        return true;
    }

    // Read the file into memory, updating the key if found
    std::vector<std::string> lines;
    std::string line;
    bool keyFound = false;

    while (std::getline(inFile, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            lines.push_back(line);
            continue;
        }

        // Parse key=value pairs
        size_t equalsPos = line.find('=');
        if (equalsPos != std::string::npos) {
            std::string lineKey = line.substr(0, equalsPos);
            if (lineKey == key) {
                // Update the value for this key
                lines.push_back(key + "=" + value);
                keyFound = true;
            } else {
                // Keep the line as is
                lines.push_back(line);
            }
        } else {
            // Not a key-value pair, keep as is
            lines.push_back(line);
        }
    }

    inFile.close();

    // If the key wasn't found, add it to the end
    if (!keyFound) {
        lines.push_back(key + "=" + value);
    }

    // Write the updated content back to the file
    std::ofstream outFile(configPath);
    if (!outFile.is_open()) {
        brls::Logger::error("Failed to open config file for writing: {}", configPath);
        return false;
    }

    for (const auto& line : lines) {
        outFile << line << "\n";
    }

    return true;
}

bool Config::setBool(const std::string& key, bool value) {
    return updateConfigKey(key, value ? "1" : "0");
}

int Config::getInt(const std::string& key, int defaultValue) {
    auto config = readConfigFile();
    auto it = config.find(key);

    if (it == config.end()) {
        return defaultValue;
    }

    // Convert string to int
    try {
        return std::stoi(it->second);
    } catch (const std::exception& e) {
        brls::Logger::error("Failed to convert config value to int: {}", e.what());
        return defaultValue;
    }
}

bool Config::setInt(const std::string& key, int value) {
    return updateConfigKey(key, std::to_string(value));
}

} // namespace pkdex
