#include "config.h"
#include "util.h"

#include <cstdio>
#include <cstdlib>
#include <map>

namespace {

std::map<std::string, std::string> g_values;

void save() {
    util::ensureDir(config::DIR);
    FILE* f = fopen(config::PATH, "wb");
    if (!f) return;
    fputs("# pkDex configuration file\n# This file is automatically generated\n\n", f);
    for (const auto& [k, v] : g_values)
        fprintf(f, "%s=%s\n", k.c_str(), v.c_str());
    fclose(f);
}

} // anonymous namespace

namespace config {

void load() {
    g_values.clear();
    std::string text;
    if (!util::readFile(PATH, text)) return;
    for (const std::string& raw : util::split(text, "\n")) {
        const std::string line = util::trim(raw);
        if (line.empty() || line[0] == '#' || line[0] == ';') continue;
        const size_t eq = line.find('=');
        if (eq == std::string::npos) continue;
        g_values[line.substr(0, eq)] = line.substr(eq + 1);
    }
}

bool getBool(const std::string& key, bool def) {
    auto it = g_values.find(key);
    if (it == g_values.end()) return def;
    const std::string& v = it->second;
    return v == "1" || v == "true" || v == "yes" || v == "on";
}

void setBool(const std::string& key, bool value) {
    g_values[key] = value ? "1" : "0";
    save();
}

int getInt(const std::string& key, int def) {
    auto it = g_values.find(key);
    if (it == g_values.end() || it->second.empty()) return def;
    char* end = nullptr;
    const long v = strtol(it->second.c_str(), &end, 10);
    return (end && *end == '\0') ? static_cast<int>(v) : def;
}

void setInt(const std::string& key, int value) {
    g_values[key] = std::to_string(value);
    save();
}

std::string getString(const std::string& key, const std::string& def) {
    auto it = g_values.find(key);
    return it == g_values.end() ? def : it->second;
}

void setString(const std::string& key, const std::string& value) {
    g_values[key] = value;
    save();
}

} // namespace config
