#include "tracker.h"
#include "dex.h"
#include "util.h"

#include <cstdio>
#include <map>
#include <unordered_map>

namespace {

constexpr const char* DIR = "sdmc:/switch/pkDex";

// region -> (key -> flags). An ordered map per region, so the file is written
// in a stable order.
std::unordered_map<std::string, std::map<std::string, Capture>> g_cache;
unsigned g_version = 1;

std::string filePath(const std::string& region) { return std::string(DIR) + "/" + tracker::fileName(region); }
std::string keyOf(const std::string& region, const std::string& regional) { return region + "_" + regional; }

// "1,0,0,1". A file from before the four states holds a lone "1".
Capture parseCapture(const std::string& value) {
    Capture c;
    const auto parts = util::split(value, ",");
    for (size_t i = 0; i < parts.size() && i < Capture::Count; i++)
        c.flags[i] = util::trim(parts[i]) == "1";
    return c;
}

std::string formatCapture(const Capture& c) {
    std::string s;
    for (int i = 0; i < Capture::Count; i++) {
        if (i) s += ',';
        s += c.flags[i] ? '1' : '0';
    }
    return s;
}

std::map<std::string, Capture>& regionMap(const std::string& region) {
    auto it = g_cache.find(region);
    if (it != g_cache.end()) return it->second;
    auto& m = g_cache[region];
    std::string text;
    if (util::readFile(filePath(region), text)) {
        for (const std::string& raw : util::split(text, "\n")) {
            const std::string line = util::trim(raw);
            if (line.empty() || line[0] == '#' || line[0] == ';') continue;
            const size_t eq = line.find('=');
            if (eq == std::string::npos) continue;
            m[line.substr(0, eq)] = parseCapture(line.substr(eq + 1));
        }
    }
    return m;
}

bool saveRegion(const std::string& region) {
    g_version++;
    util::ensureDir(DIR);
    FILE* f = fopen(filePath(region).c_str(), "wb");
    if (!f) return false;
    fprintf(f, "# pkDex Pokémon tracker file for %s region\n# This file is automatically generated\n\n",
            region.c_str());
    for (const auto& [k, c] : regionMap(region))
        fprintf(f, "%s=%s\n", k.c_str(), formatCapture(c).c_str());
    return fclose(f) == 0;
}

} // anonymous namespace

namespace tracker {

std::string fileName(const std::string& region) { return "pkDex.tracker." + region + ".ini"; }

Capture get(const std::string& region, const std::string& regional) {
    const auto& m = regionMap(region);
    auto it = m.find(keyOf(region, regional));
    return it == m.end() ? Capture{} : it->second;
}

void set(const std::string& region, const std::string& regional, const Capture& c) {
    regionMap(region)[keyOf(region, regional)] = c;
    saveRegion(region);
}

void bulkSet(const std::string& region, const std::vector<std::string>& regionals, int state, bool value) {
    auto& m = regionMap(region);
    for (const auto& r : regionals)
        m[keyOf(region, r)].set(state, value);
    saveRegion(region);
}

bool resetRegion(const std::string& region) {
    regionMap(region).clear();
    return saveRegion(region);
}

bool resetAll() {
    bool ok = true;
    for (const auto& r : dex::regions())
        ok = resetRegion(r.id) && ok;
    return ok;
}

Counts counts(const std::string& region, const std::vector<Pokemon>& list) {
    Counts out;
    const auto& m = regionMap(region);
    for (const auto& p : list) {
        auto it = m.find(keyOf(region, p.regional));
        if (it == m.end()) continue;
        const Capture& c = it->second;
        if (c.any()) out.any++;
        for (int s = 0; s < Capture::Count; s++)
            if (c.flags[s]) out.state[s]++;
    }
    return out;
}

unsigned version() { return g_version; }

} // namespace tracker
