#include "data/pokemon_tracker.hpp"
#include <borealis.hpp>
#include <fstream>
#include <filesystem>
#include <sstream>
#include <nlohmann/json.hpp>

namespace pkdex {

std::string PokemonTracker::getTrackerFilePath(const std::string& region) {
    // Create the config directory if it doesn't exist
    std::filesystem::path configDir = "/switch/pkDex";
    if (!std::filesystem::exists(configDir)) {
        try {
            std::filesystem::create_directories(configDir);
        } catch (const std::exception& e) {
            brls::Logger::error("Failed to create config directory: {}", e.what());
            return "";
        }
    }

    return configDir / ("pkDex.tracker." + region + ".ini");
}

std::vector<std::string> PokemonTracker::getAllRegions() {
    // Default regions if the file doesn't exist or can't be loaded
    std::vector<std::string> defaultRegions = {"kanto", "johto", "hoenn", "sinnoh", "sinnoh_arceus", "galar", "paldea"};

    // Load the JSON file
    std::string filePath = "romfs:/data/regions.json";
    std::ifstream file(filePath);
    if (!file.is_open()) {
        brls::Logger::error("Failed to load regions data from {}", filePath);
        return defaultRegions;
    }

    nlohmann::json doc;
    try {
        file >> doc;
    } catch (const std::exception& e) {
        brls::Logger::error("Failed to parse regions data from {}: {}", filePath, e.what());
        return defaultRegions;
    }

    if (!doc.is_array()) {
        brls::Logger::error("Invalid regions data file format: {}", filePath);
        return defaultRegions;
    }

    std::vector<std::string> regions;
    for (const auto& entry : doc) {
        if (entry.is_string()) {
            regions.push_back(entry.get<std::string>());
        }
    }

    // If no regions were found, use the default regions
    if (regions.empty()) {
        brls::Logger::error("No regions found in {}", filePath);
        return defaultRegions;
    }

    return regions;
}

std::map<std::string, std::string> PokemonTracker::readTrackerFile(const std::string& region) {
    std::map<std::string, std::string> tracker;
    std::string trackerPath = getTrackerFilePath(region);

    if (trackerPath.empty()) {
        return tracker;
    }

    std::ifstream file(trackerPath);
    if (!file.is_open()) {
        // File doesn't exist yet, which is fine
        return tracker;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            continue;
        }

        // Parse key=value pairs
        size_t equalsPos = line.find('=');
        if (equalsPos != std::string::npos) {
            std::string key = line.substr(0, equalsPos);
            std::string value = line.substr(equalsPos + 1);
            tracker[key] = value;
        }
    }

    return tracker;
}

bool PokemonTracker::writeTrackerFile(const std::string& region, const std::map<std::string, std::string>& tracker) {
    std::string trackerPath = getTrackerFilePath(region);

    if (trackerPath.empty()) {
        return false;
    }

    std::ofstream file(trackerPath);
    if (!file.is_open()) {
        brls::Logger::error("Failed to open tracker file for writing: {}", trackerPath);
        return false;
    }

    // Write header
    file << "# pkDex Pokémon tracker file for " << region << " region\n";
    file << "# This file is automatically generated\n\n";

    // Write key-value pairs
    for (const auto& [key, value] : tracker) {
        file << key << "=" << value << "\n";
    }

    return true;
}

bool PokemonTracker::updateTrackerKey(const std::string& region, const std::string& key, const std::string& value) {
    std::string trackerPath = getTrackerFilePath(region);

    if (trackerPath.empty()) {
        return false;
    }

    // Read the existing file
    std::ifstream inFile(trackerPath);
    if (!inFile.is_open()) {
        // File doesn't exist yet, create it with just this key-value pair
        std::ofstream outFile(trackerPath);
        if (!outFile.is_open()) {
            brls::Logger::error("Failed to create tracker file: {}", trackerPath);
            return false;
        }

        outFile << "# pkDex Pokémon tracker file for " << region << " region\n";
        outFile << "# This file is automatically generated\n\n";
        outFile << key << "=" << value << "\n";
        return true;
    }

    // Read the file into memory, updating the key if found
    std::vector<std::string> lines;
    std::string line;
    bool keyFound = false;

    while (std::getline(inFile, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            lines.push_back(line);
            continue;
        }

        // Parse key=value pairs
        size_t equalsPos = line.find('=');
        if (equalsPos != std::string::npos) {
            std::string lineKey = line.substr(0, equalsPos);
            if (lineKey == key) {
                // Update the value for this key
                lines.push_back(key + "=" + value);
                keyFound = true;
            } else {
                // Keep the line as is
                lines.push_back(line);
            }
        } else {
            // Not a key-value pair, keep as is
            lines.push_back(line);
        }
    }

    inFile.close();

    // If the key wasn't found, add it to the end
    if (!keyFound) {
        lines.push_back(key + "=" + value);
    }

    // Write the updated content back to the file
    std::ofstream outFile(trackerPath);
    if (!outFile.is_open()) {
        brls::Logger::error("Failed to open tracker file for writing: {}", trackerPath);
        return false;
    }

    for (const auto& line : lines) {
        outFile << line << "\n";
    }

    return true;
}


std::string PokemonTracker::generateKey(const std::string& region, const std::string& regionalDexNumber) {
    return region + "_" + regionalDexNumber;
}


// Convert string value to CaptureStates struct (comma-separated 1/0/0/1)
static CaptureStates stringToCaptureStates(const std::string& value) {
    CaptureStates states;
    std::istringstream ss(value);
    std::string token;
    int idx = 0;
    while (std::getline(ss, token, ',') && idx < 4) {
        bool val = (token == "1");
        switch (idx) {
            case 0: states.normal = val; break;
            case 1: states.shiny = val; break;
            case 2: states.alpha = val; break;
            case 3: states.shinyAlpha = val; break;
        }
        idx++;
    }
    return states;
}

// Convert CaptureStates struct to string value
static std::string captureStatesToString(const CaptureStates& states) {
    return std::string(states.normal ? "1" : "0") + "," +
           (states.shiny ? "1" : "0") + "," +
           (states.alpha ? "1" : "0") + "," +
           (states.shinyAlpha ? "1" : "0");
}

CaptureStates PokemonTracker::getCaptureStates(const std::string& region, const std::string& regionalDexNumber) {
    auto tracker = readTrackerFile(region);
    std::string key = generateKey(region, regionalDexNumber);
    auto it = tracker.find(key);
    if (it == tracker.end()) {
        return CaptureStates{};
    }
    return stringToCaptureStates(it->second);
}

CaptureStates PokemonTracker::toggleCaptureState(const std::string& region, const std::string& regionalDexNumber, int stateIndex) {
    std::string key = generateKey(region, regionalDexNumber);
    CaptureStates states = getCaptureStates(region, regionalDexNumber);
    switch (stateIndex) {
        case 0: states.normal = !states.normal; break;
        case 1: states.shiny = !states.shiny; break;
        case 2: states.alpha = !states.alpha; break;
        case 3: states.shinyAlpha = !states.shinyAlpha; break;
        default: break;
    }
    updateTrackerKey(region, key, captureStatesToString(states));
    return states;
}

void PokemonTracker::bulkSetCaptureState(const std::string& region, const std::vector<std::string>& regionalDexNumbers, int stateIndex, bool value) {
    // Read the tracker file once
    auto tracker = readTrackerFile(region);

    // Update all entries
    for (const auto& dexNumber : regionalDexNumbers) {
        std::string key = generateKey(region, dexNumber);
        CaptureStates states;

        auto it = tracker.find(key);
        if (it != tracker.end()) {
            // Parse existing states
            std::istringstream ss(it->second);
            std::string token;
            int idx = 0;
            while (std::getline(ss, token, ',') && idx < 4) {
                bool val = (token == "1");
                switch (idx) {
                    case 0: states.normal = val; break;
                    case 1: states.shiny = val; break;
                    case 2: states.alpha = val; break;
                    case 3: states.shinyAlpha = val; break;
                }
                idx++;
            }
        }

        // Set the specific state
        switch (stateIndex) {
            case 0: states.normal = value; break;
            case 1: states.shiny = value; break;
            case 2: states.alpha = value; break;
            case 3: states.shinyAlpha = value; break;
            default: break;
        }

        // Convert back to string
        std::string stateStr = std::string(states.normal ? "1" : "0") + "," +
                               (states.shiny ? "1" : "0") + "," +
                               (states.alpha ? "1" : "0") + "," +
                               (states.shinyAlpha ? "1" : "0");
        tracker[key] = stateStr;
    }

    // Write the tracker file once
    writeTrackerFile(region, tracker);
}

bool PokemonTracker::resetAllCaptureStatus() {
    bool success = true;
    std::map<std::string, std::string> emptyTracker;

    // Reset the tracker file for each region
    for (const auto& region : getAllRegions()) {
        if (!writeTrackerFile(region, emptyTracker)) {
            //brls::Logger::error("Failed to reset tracker file for region: {}", region);
            success = false;
        }
    }

    return success;
}

bool PokemonTracker::resetRegionCaptureStatus(const std::string& region) {
    std::map<std::string, std::string> emptyTracker;

    // Reset the tracker file for the specified region
    return writeTrackerFile(region, emptyTracker);
}

} // namespace pkdex
