#include "data/pokemon_tracker.hpp"
#include <borealis.hpp>
#include <fstream>
#include <filesystem>
#include <sstream>

namespace pkdex {

std::string PokemonTracker::getTrackerFilePath() {
    // Create the config directory if it doesn't exist
    std::filesystem::path configDir = "/switch/pkDex";
    if (!std::filesystem::exists(configDir)) {
        try {
            std::filesystem::create_directories(configDir);
        } catch (const std::exception& e) {
            brls::Logger::error("Failed to create config directory: {}", e.what());
            return "";
        }
    }

    return configDir / "pkDex.tracker.ini";
}

std::map<std::string, std::string> PokemonTracker::readTrackerFile() {
    std::map<std::string, std::string> tracker;
    std::string trackerPath = getTrackerFilePath();

    if (trackerPath.empty()) {
        return tracker;
    }

    std::ifstream file(trackerPath);
    if (!file.is_open()) {
        // File doesn't exist yet, which is fine
        return tracker;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            continue;
        }

        // Parse key=value pairs
        size_t equalsPos = line.find('=');
        if (equalsPos != std::string::npos) {
            std::string key = line.substr(0, equalsPos);
            std::string value = line.substr(equalsPos + 1);
            tracker[key] = value;
        }
    }

    return tracker;
}

bool PokemonTracker::writeTrackerFile(const std::map<std::string, std::string>& tracker) {
    std::string trackerPath = getTrackerFilePath();

    if (trackerPath.empty()) {
        return false;
    }

    std::ofstream file(trackerPath);
    if (!file.is_open()) {
        brls::Logger::error("Failed to open tracker file for writing: {}", trackerPath);
        return false;
    }

    // Write header
    file << "# pkDex Pokémon tracker file\n";
    file << "# This file is automatically generated\n\n";

    // Write key-value pairs
    for (const auto& [key, value] : tracker) {
        file << key << "=" << value << "\n";
    }

    return true;
}

bool PokemonTracker::updateTrackerKey(const std::string& key, const std::string& value) {
    std::string trackerPath = getTrackerFilePath();

    if (trackerPath.empty()) {
        return false;
    }

    // Read the existing file
    std::ifstream inFile(trackerPath);
    if (!inFile.is_open()) {
        // File doesn't exist yet, create it with just this key-value pair
        std::ofstream outFile(trackerPath);
        if (!outFile.is_open()) {
            brls::Logger::error("Failed to create tracker file: {}", trackerPath);
            return false;
        }

        outFile << "# pkDex Pokémon tracker file\n";
        outFile << "# This file is automatically generated\n\n";
        outFile << key << "=" << value << "\n";
        return true;
    }

    // Read the file into memory, updating the key if found
    std::vector<std::string> lines;
    std::string line;
    bool keyFound = false;

    while (std::getline(inFile, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            lines.push_back(line);
            continue;
        }

        // Parse key=value pairs
        size_t equalsPos = line.find('=');
        if (equalsPos != std::string::npos) {
            std::string lineKey = line.substr(0, equalsPos);
            if (lineKey == key) {
                // Update the value for this key
                lines.push_back(key + "=" + value);
                keyFound = true;
            } else {
                // Keep the line as is
                lines.push_back(line);
            }
        } else {
            // Not a key-value pair, keep as is
            lines.push_back(line);
        }
    }

    inFile.close();

    // If the key wasn't found, add it to the end
    if (!keyFound) {
        lines.push_back(key + "=" + value);
    }

    // Write the updated content back to the file
    std::ofstream outFile(trackerPath);
    if (!outFile.is_open()) {
        brls::Logger::error("Failed to open tracker file for writing: {}", trackerPath);
        return false;
    }

    for (const auto& line : lines) {
        outFile << line << "\n";
    }

    return true;
}

std::string PokemonTracker::generateKey(const std::string& region, const std::string& regionalDexNumber) {
    return region + "_" + regionalDexNumber;
}

bool PokemonTracker::isCaptured(const std::string& region, const std::string& regionalDexNumber) {
    auto tracker = readTrackerFile();
    std::string key = generateKey(region, regionalDexNumber);
    auto it = tracker.find(key);

    if (it == tracker.end()) {
        return false; // Not found, so not captured
    }

    // Convert string to bool
    return it->second == "1";
}

bool PokemonTracker::toggleCaptureStatus(const std::string& region, const std::string& regionalDexNumber) {
    std::string key = generateKey(region, regionalDexNumber);
    bool currentStatus = isCaptured(region, regionalDexNumber);
    bool newStatus = !currentStatus;

    // Update the tracker file
    updateTrackerKey(key, newStatus ? "1" : "0");

    return newStatus;
}

bool PokemonTracker::resetAllCaptureStatus() {
    std::string trackerPath = getTrackerFilePath();

    if (trackerPath.empty()) {
        return false;
    }

    // Create an empty map and write it to the tracker file
    std::map<std::string, std::string> emptyTracker;
    return writeTrackerFile(emptyTracker);
}

} // namespace pkdex
